services:

    # Logger

    tms_payment.logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [tms_payment]
        calls:
            - [pushHandler, ["@tms_payment.logger_handler"]]

    tms_payment.logger_handler:
        class: Monolog\Handler\StreamHandler
        # DEBUG:100, INFO:200, NOTICE:250, WARNING:300, ERROR:400, CRITICAL:500, ALERT:550, EMERGENCY:600
        arguments: ["%payments.logs_dir%/autoresponse_%kernel.environment%.log", 100]


    # Registry

    tms_payment.backend_registry:
        class: Tms\Bundle\PaymentBundle\Backend\PaymentBackendRegistry

    tms_payment.callback_registry:
        class: Tms\Bundle\PaymentBundle\Callback\PaymentCallbackRegistry


    # Backend

    tms_payment.backend.sogenactif:
        class: Tms\Bundle\PaymentBundle\Backend\AtosSipsBinPaymentBackend
        arguments:
            -
                pathfile: "%payments.sogenactif_pathfile%"
                request_bin_path: "@=service('kernel').locateResource('@TmsPaymentBundle/Resources/sips/atos/bin/static/request')"
                response_bin_path: "@=service('kernel').locateResource('@TmsPaymentBundle/Resources/sips/atos/bin/static/response')"
        tags:
            - { name: tms_payment.backend, alias: sogenactif }

    tms_payment.backend.scellius:
        class: Tms\Bundle\PaymentBundle\Backend\AtosSipsBinPaymentBackend
        arguments:
            -
                pathfile: "%payments.scellius_pathfile%"
                request_bin_path: "@=service('kernel').locateResource('@TmsPaymentBundle/Resources/sips/atos/bin/static/request')"
                response_bin_path: "@=service('kernel').locateResource('@TmsPaymentBundle/Resources/sips/atos/bin/static/response')"
        tags:
            - { name: tms_payment.backend, alias: scellius }

    tms_payment.backend.mercanet:
        class: Tms\Bundle\PaymentBundle\Backend\AtosSipsSealPaymentBackend
        arguments:
            - { keys_path: "%payments.mercanet_keys_path%", web_server: "%payments.mercanet_web_server%" }
            - "@twig"
        tags:
            - { name: tms_payment.backend, alias: mercanet }

    tms_payment.backend.paybox:
        class: Tms\Bundle\PaymentBundle\Backend\PayboxPaymentBackend
        arguments:
            - { keys_path: "%payments.paybox_keys_path%", web_servers: "%payments.paybox_web_servers%" }
            - "@twig"
        tags:
            - { name: tms_payment.backend, alias: paybox }


    # Callback

    tms_payment.callback.update_order:
        class: Tms\Bundle\PaymentBundle\Callback\UpdateOrderPaymentCallback
        arguments: ["@tms_rest_client.hypermedia.crawler"]
        tags:
            - { name: tms_payment.callback, alias: update_order }

    tms_payment.callback.create_participation:
        class: Tms\Bundle\PaymentBundle\Callback\CreateParticipationPaymentCallback
        arguments: ["@tms_rest_client.hypermedia.crawler"]
        tags:
            - { name: tms_payment.callback, alias: create_participation }
